# Copyright (c) 2024 Tomislav Milkovic
# SPDX-License-Identifier: MIT

manifest:
  self:
    path: zephyr-xio-sensor-fusion
    # Also update this module's git submodules when running "west update" command:
    submodules: true
